### ISSUE TITLE
`connection.write` when `connection` is `null`

### ISSUE THREAD

**Issue by voltrevo** [thepatrick/octo-sansa#1]
Yo. I managed to hit this part of the code:

https://github.com/thepatrick/octo-sansa/blob/876de16204ef93b74f3ab8b702df525d2a2bc4fd/lib/client.js#L113

With `connection` being `null`, throwing an exception. Is this a symptom of something going wrong at another layer or should this code be checking whether `connection` is `null` before writing?

**Comment by thissophie** [comment]
That means someone `ask`'d after the connection was closed, but yeah it should probably check and throw an exception with useful info or call the completion handler with said error. 

Thanks for letting me know :)

**Comment by thissophie** [comment]
Fixed in v2
